// <auto-generated />
using System;
using CinemaAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CinemaAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260629035702_AddEmailField")]
    partial class AddEmailField
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CinemaAPI.Models.Film", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Deskripsi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Durasi")
                        .HasColumnType("int");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JudulFilm")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Films");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Deskripsi = "Pencuri yang mencuri rahasia lewat mimpi.",
                            Durasi = 148,
                            Genre = "Sci-Fi",
                            JudulFilm = "Inception"
                        },
                        new
                        {
                            Id = 2,
                            Deskripsi = "Batman melawan ancaman Joker di Gotham.",
                            Durasi = 152,
                            Genre = "Action",
                            JudulFilm = "The Dark Knight"
                        },
                        new
                        {
                            Id = 3,
                            Deskripsi = "Perjalanan ruang angkasa demi menyelamatkan umat manusia.",
                            Durasi = 169,
                            Genre = "Sci-Fi",
                            JudulFilm = "Interstellar"
                        });
                });

            modelBuilder.Entity("CinemaAPI.Models.JadwalFilm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FilmId")
                        .HasColumnType("int");

                    b.Property<decimal>("HargaTiket")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StudioId")
                        .HasColumnType("int");

                    b.Property<DateTime>("WaktuTayang")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FilmId");

                    b.HasIndex("StudioId");

                    b.ToTable("JadwalFilms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FilmId = 1,
                            HargaTiket = 75000m,
                            StudioId = 1,
                            WaktuTayang = new DateTime(2026, 7, 1, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            FilmId = 2,
                            HargaTiket = 60000m,
                            StudioId = 2,
                            WaktuTayang = new DateTime(2026, 7, 1, 16, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            FilmId = 3,
                            HargaTiket = 50000m,
                            StudioId = 3,
                            WaktuTayang = new DateTime(2026, 7, 1, 19, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("CinemaAPI.Models.Studio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FasilitasTambahan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Kapasitas")
                        .HasColumnType("int");

                    b.Property<string>("NamaStudio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Studios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FasilitasTambahan = "Dolby Atmos, Recliner Seats",
                            Kapasitas = 50,
                            NamaStudio = "Studio 1 Premiere"
                        },
                        new
                        {
                            Id = 2,
                            FasilitasTambahan = "Layar IMAX 3D",
                            Kapasitas = 150,
                            NamaStudio = "Studio 2 IMAX"
                        },
                        new
                        {
                            Id = 3,
                            FasilitasTambahan = "AC, Kursi Standar",
                            Kapasitas = 100,
                            NamaStudio = "Studio 3 Reguler"
                        });
                });

            modelBuilder.Entity("CinemaAPI.Models.Tiket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("JadwalFilmId")
                        .HasColumnType("int");

                    b.Property<string>("NomorKursi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusTiket")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("JadwalFilmId");

                    b.ToTable("Tikets");
                });

            modelBuilder.Entity("CinemaAPI.Models.Transaksi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MetodePembayaran")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusPembayaran")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TiketId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TiketId");

                    b.ToTable("Transaksis");
                });

            modelBuilder.Entity("CinemaAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@cinema.com",
                            PasswordHash = "admin123",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Email = "user@cinema.com",
                            PasswordHash = "user123",
                            Role = "User",
                            Username = "user"
                        });
                });

            modelBuilder.Entity("CinemaAPI.Models.JadwalFilm", b =>
                {
                    b.HasOne("CinemaAPI.Models.Film", "Film")
                        .WithMany()
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CinemaAPI.Models.Studio", "Studio")
                        .WithMany()
                        .HasForeignKey("StudioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Film");

                    b.Navigation("Studio");
                });

            modelBuilder.Entity("CinemaAPI.Models.Tiket", b =>
                {
                    b.HasOne("CinemaAPI.Models.JadwalFilm", "JadwalFilm")
                        .WithMany()
                        .HasForeignKey("JadwalFilmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JadwalFilm");
                });

            modelBuilder.Entity("CinemaAPI.Models.Transaksi", b =>
                {
                    b.HasOne("CinemaAPI.Models.Tiket", "Tiket")
                        .WithMany()
                        .HasForeignKey("TiketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tiket");
                });
#pragma warning restore 612, 618
        }
    }
}
